export const QUESTION = '/question'
export const ANSWER = '/answer'
export const MESSAGE = '/message'
export const DEPARTMENT = '/department'
export const HOOLIGAN = '/hooligan'
export const CANDIDATE_TYPE = '/candidatetype'
